// CherryJS ESLint config — flat config (ESLint 9+).
//
// Scope: only `convex/` files. Frontend (`app/`) is intentionally NOT
// linted by ESLint to avoid duplicating the architectural test
// enforcement that already covers structure, naming, and patterns.
//
// The Convex plugin catches a few categories the architectural tests
// don't:
//   - `no-old-registered-function-syntax` — `query(handler)` (positional)
//     vs `query({ handler })` (object); flagged at runtime by Convex CLI
//     but having it as an editor squiggle is faster.
//   - `require-args-validator` — every public function must declare an
//     `args:` validator. Forgetting this lets garbage data hit the DB.
//   - `explicit-table-ids` — `v.id("users")` instead of `v.string()` for
//     foreign-key fields. Catches an entire class of dangling-reference
//     bugs.
//   - `no-collect-in-query` — `.collect()` inside a query is a perf
//     foot-gun once the table grows. Pair with our `.collect().length`
//     architectural rule which catches a stricter subset.
//
// Files generated by Convex (`_generated/`) and our `@ts-nocheck` domain
// files are excluded so the linter doesn't shout about scaffolding.
import convex from "@convex-dev/eslint-plugin";
import tseslint from "typescript-eslint";

export default [
  // Global ignores — applies to ESLint's default file discovery before
  // any per-config `files` glob is matched.
  {
    ignores: [
      "convex/_generated/**",
      "node_modules/**",
      "dist/**",
      ".output/**",
      // Domain files use `@ts-nocheck` to dodge Convex issue #53. ESLint
      // would still flag them, so opt them out at the lint level too.
      "convex/apps/**/*Business.ts",
      "convex/apps/**/*Channel.ts",
      "convex/apps/**/*Integration.ts",
      "convex/apps/**/*Model.ts",
      "convex/core/**/*Business.ts",
      "convex/core/**/*Channel.ts",
      "convex/core/**/*Model.ts",
    ],
  },
  {
    files: ["convex/**/*.ts"],
    languageOptions: {
      parser: tseslint.parser,
      parserOptions: {
        ecmaVersion: "latest",
        sourceType: "module",
      },
    },
    plugins: {
      "@convex-dev": convex,
    },
    rules: {
      "@convex-dev/no-old-registered-function-syntax": "error",
      "@convex-dev/require-args-validator": "error",
      "@convex-dev/explicit-table-ids": "error",
      "@convex-dev/no-collect-in-query": "warn",
      "@convex-dev/import-wrong-runtime": "off",
    },
  },
];
