import tailwindcss from "@tailwindcss/vite";
import { tanstackStart } from "@tanstack/react-start/plugin/vite";
import viteReact from "@vitejs/plugin-react";
import { defineConfig } from "vite";
import tsconfigPaths from "vite-tsconfig-paths";

/**
 * Cloudflare deployment via Alchemy is opt-in.
 * - Local dev / build (default): plain Vite + TanStack Start
 * - Cloudflare deploy: set ALCHEMY=1 (handled automatically by `alchemy deploy`)
 *
 * Alchemy needs `.alchemy/local/wrangler.jsonc` which is generated by
 * `alchemy dev` / `alchemy deploy`. Without it, the plugin throws on import,
 * so we only load it when actually deploying.
 */
const useAlchemy = process.env.ALCHEMY === "1";

export default defineConfig(async () => {
  const plugins = [
    tsconfigPaths({
      root: process.cwd(),
      ignoreConfigErrors: true,
    }),
    tailwindcss(),
    tanstackStart({
      srcDirectory: "app",
    }),
    viteReact(),
  ];

  if (useAlchemy) {
    const { default: alchemy } = await import("alchemy/cloudflare/tanstack-start");
    plugins.push(alchemy());
  }

  return {
    plugins,
    resolve: {
      dedupe: ["convex/react", "convex"],
    },
    // When alchemy is on, @cloudflare/vite-plugin sets resolve.noExternal: true
    // (bundles everything for the worker runtime). Setting our own ssr.noExternal
    // alongside it causes Vite to merge into [true, ...strings] which crashes
    // the commonjs filter ("filename.replace is not a function"). So only set
    // ssr.noExternal in plain build mode.
    ...(useAlchemy
      ? {}
      : { ssr: { noExternal: ["@convex-dev/better-auth"] } }),
    clearScreen: false,
  };
});
