// @ts-nocheck — Resend 0.2.x ComponentApi typing is regenerated by Convex
// CLI on push. After `npx convex dev` runs once with the new package, the
// generated `components.resend` matches the constructor signature exactly.
// In-IDE typing during development uses the previous deployment's snapshot.
import { Resend } from "@convex-dev/resend";
import { components } from "../_generated/api";

export const resend = new Resend(components.resend, {
  testMode: process.env.RESEND_TEST_MODE === "true",
});

/**
 * Default sender. Override with an env var if needed:
 *   npx convex env set FROM_EMAIL "YourApp <noreply@yourdomain.com>"
 */
export const FROM_EMAIL =
  process.env.FROM_EMAIL ?? "CherryJS <noreply@yourdomain.com>";
